#include "move.h"
#include "main.h"
#include "stdio.h"
#include "tim.h"
#include "gpio.h"


//A高B低为正转，反之为反转,1,2为前轮，3，4为后轮，对应左前右前左后右后。
void FORWARD_MOVE(void){
	HAL_GPIO_WritePin(MOTOR1A_GPIO_Port,MOTOR1A_Pin,GPIO_PIN_SET);
	HAL_GPIO_WritePin(MOTOR1B_GPIO_Port,MOTOR1B_Pin,GPIO_PIN_RESET);
	
	HAL_GPIO_WritePin(MOTOR2A_GPIO_Port,MOTOR2A_Pin,GPIO_PIN_SET);
	HAL_GPIO_WritePin(MOTOR2B_GPIO_Port,MOTOR2B_Pin,GPIO_PIN_RESET);
	
	HAL_GPIO_WritePin(MOTOR3A_GPIO_Port,MOTOR3A_Pin,GPIO_PIN_SET);
	HAL_GPIO_WritePin(MOTOR3B_GPIO_Port,MOTOR3B_Pin,GPIO_PIN_RESET);
	
	HAL_GPIO_WritePin(MOTOR4A_GPIO_Port,MOTOR4A_Pin,GPIO_PIN_SET);
	HAL_GPIO_WritePin(MOTOR4B_GPIO_Port,MOTOR4B_Pin,GPIO_PIN_RESET);
}

void BACK_MOVE(void){
	HAL_GPIO_WritePin(MOTOR1A_GPIO_Port,MOTOR1A_Pin,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(MOTOR1B_GPIO_Port,MOTOR1B_Pin,GPIO_PIN_SET);
	
	HAL_GPIO_WritePin(MOTOR2A_GPIO_Port,MOTOR2A_Pin,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(MOTOR2B_GPIO_Port,MOTOR2B_Pin,GPIO_PIN_SET);
	
	HAL_GPIO_WritePin(MOTOR3A_GPIO_Port,MOTOR3A_Pin,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(MOTOR3B_GPIO_Port,MOTOR3B_Pin,GPIO_PIN_SET);
	
	HAL_GPIO_WritePin(MOTOR4A_GPIO_Port,MOTOR4A_Pin,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(MOTOR4B_GPIO_Port,MOTOR4B_Pin,GPIO_PIN_SET);
}

void RIGHT_MOVE(void){
	HAL_GPIO_WritePin(MOTOR1A_GPIO_Port,MOTOR1A_Pin,GPIO_PIN_SET);
	HAL_GPIO_WritePin(MOTOR1B_GPIO_Port,MOTOR1B_Pin,GPIO_PIN_RESET);
	
	HAL_GPIO_WritePin(MOTOR2A_GPIO_Port,MOTOR2A_Pin,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(MOTOR2B_GPIO_Port,MOTOR2B_Pin,GPIO_PIN_SET);
	
	HAL_GPIO_WritePin(MOTOR3A_GPIO_Port,MOTOR3A_Pin,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(MOTOR3B_GPIO_Port,MOTOR3B_Pin,GPIO_PIN_SET);
	
	HAL_GPIO_WritePin(MOTOR4A_GPIO_Port,MOTOR4A_Pin,GPIO_PIN_SET);
	HAL_GPIO_WritePin(MOTOR4B_GPIO_Port,MOTOR4B_Pin,GPIO_PIN_RESET);
}

void LEFT_MOVE(void){
	HAL_GPIO_WritePin(MOTOR1A_GPIO_Port,MOTOR1A_Pin,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(MOTOR1B_GPIO_Port,MOTOR1B_Pin,GPIO_PIN_SET);
	
	HAL_GPIO_WritePin(MOTOR2A_GPIO_Port,MOTOR2A_Pin,GPIO_PIN_SET);
	HAL_GPIO_WritePin(MOTOR2B_GPIO_Port,MOTOR2B_Pin,GPIO_PIN_RESET);
	
	HAL_GPIO_WritePin(MOTOR3A_GPIO_Port,MOTOR3A_Pin,GPIO_PIN_SET);
	HAL_GPIO_WritePin(MOTOR3B_GPIO_Port,MOTOR3B_Pin,GPIO_PIN_RESET);
	
	HAL_GPIO_WritePin(MOTOR4A_GPIO_Port,MOTOR4A_Pin,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(MOTOR4B_GPIO_Port,MOTOR4B_Pin,GPIO_PIN_SET);
}

void LEFT_ROTAY(void){
	HAL_GPIO_WritePin(MOTOR1A_GPIO_Port,MOTOR1A_Pin,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(MOTOR1B_GPIO_Port,MOTOR1B_Pin,GPIO_PIN_SET);
	
	HAL_GPIO_WritePin(MOTOR2A_GPIO_Port,MOTOR2A_Pin,GPIO_PIN_SET);
	HAL_GPIO_WritePin(MOTOR2B_GPIO_Port,MOTOR2B_Pin,GPIO_PIN_RESET);
	
	HAL_GPIO_WritePin(MOTOR3A_GPIO_Port,MOTOR3A_Pin,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(MOTOR3B_GPIO_Port,MOTOR3B_Pin,GPIO_PIN_SET);
	
	HAL_GPIO_WritePin(MOTOR4A_GPIO_Port,MOTOR4A_Pin,GPIO_PIN_SET);
	HAL_GPIO_WritePin(MOTOR4B_GPIO_Port,MOTOR4B_Pin,GPIO_PIN_RESET);
}

void RIGHT_ROTAY(void){
	HAL_GPIO_WritePin(MOTOR1A_GPIO_Port,MOTOR1A_Pin,GPIO_PIN_SET);
	HAL_GPIO_WritePin(MOTOR1B_GPIO_Port,MOTOR1B_Pin,GPIO_PIN_RESET);
	
	HAL_GPIO_WritePin(MOTOR2A_GPIO_Port,MOTOR2A_Pin,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(MOTOR2B_GPIO_Port,MOTOR2B_Pin,GPIO_PIN_SET);
	
	HAL_GPIO_WritePin(MOTOR3A_GPIO_Port,MOTOR3A_Pin,GPIO_PIN_SET);
	HAL_GPIO_WritePin(MOTOR3B_GPIO_Port,MOTOR3B_Pin,GPIO_PIN_RESET);
	
	HAL_GPIO_WritePin(MOTOR4A_GPIO_Port,MOTOR4A_Pin,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(MOTOR4B_GPIO_Port,MOTOR4B_Pin,GPIO_PIN_SET);
}

void RIGHT_FORWARD(void){
	HAL_GPIO_WritePin(MOTOR1A_GPIO_Port,MOTOR1A_Pin,GPIO_PIN_SET);
	HAL_GPIO_WritePin(MOTOR1B_GPIO_Port,MOTOR1B_Pin,GPIO_PIN_RESET);
	
	HAL_GPIO_WritePin(MOTOR2A_GPIO_Port,MOTOR2A_Pin,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(MOTOR2B_GPIO_Port,MOTOR2B_Pin,GPIO_PIN_RESET);
	
	HAL_GPIO_WritePin(MOTOR3A_GPIO_Port,MOTOR3A_Pin,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(MOTOR3B_GPIO_Port,MOTOR3B_Pin,GPIO_PIN_RESET);
	
	HAL_GPIO_WritePin(MOTOR4A_GPIO_Port,MOTOR4A_Pin,GPIO_PIN_SET);
	HAL_GPIO_WritePin(MOTOR4B_GPIO_Port,MOTOR4B_Pin,GPIO_PIN_RESET);
}

void LEFT_FORWARD(void){
	HAL_GPIO_WritePin(MOTOR1A_GPIO_Port,MOTOR1A_Pin,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(MOTOR1B_GPIO_Port,MOTOR1B_Pin,GPIO_PIN_RESET);
	
	HAL_GPIO_WritePin(MOTOR2A_GPIO_Port,MOTOR2A_Pin,GPIO_PIN_SET);
	HAL_GPIO_WritePin(MOTOR2B_GPIO_Port,MOTOR2B_Pin,GPIO_PIN_RESET);
	
	HAL_GPIO_WritePin(MOTOR3A_GPIO_Port,MOTOR3A_Pin,GPIO_PIN_SET);
	HAL_GPIO_WritePin(MOTOR3B_GPIO_Port,MOTOR3B_Pin,GPIO_PIN_RESET);
	
	HAL_GPIO_WritePin(MOTOR4A_GPIO_Port,MOTOR4A_Pin,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(MOTOR4B_GPIO_Port,MOTOR4B_Pin,GPIO_PIN_RESET);
}

void RIGHT_BACK(void){
	HAL_GPIO_WritePin(MOTOR1A_GPIO_Port,MOTOR1A_Pin,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(MOTOR1B_GPIO_Port,MOTOR1B_Pin,GPIO_PIN_RESET);
	
	HAL_GPIO_WritePin(MOTOR2A_GPIO_Port,MOTOR2A_Pin,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(MOTOR2B_GPIO_Port,MOTOR2B_Pin,GPIO_PIN_SET);
	
	HAL_GPIO_WritePin(MOTOR3A_GPIO_Port,MOTOR3A_Pin,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(MOTOR3B_GPIO_Port,MOTOR3B_Pin,GPIO_PIN_SET);
	
	HAL_GPIO_WritePin(MOTOR4A_GPIO_Port,MOTOR4A_Pin,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(MOTOR4B_GPIO_Port,MOTOR4B_Pin,GPIO_PIN_RESET);
}

void LEFT_BACK(void){
	HAL_GPIO_WritePin(MOTOR1A_GPIO_Port,MOTOR1A_Pin,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(MOTOR1B_GPIO_Port,MOTOR1B_Pin,GPIO_PIN_SET);
	
	HAL_GPIO_WritePin(MOTOR2A_GPIO_Port,MOTOR2A_Pin,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(MOTOR2B_GPIO_Port,MOTOR2B_Pin,GPIO_PIN_RESET);
	
	HAL_GPIO_WritePin(MOTOR3A_GPIO_Port,MOTOR3A_Pin,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(MOTOR3B_GPIO_Port,MOTOR3B_Pin,GPIO_PIN_RESET);
	
	HAL_GPIO_WritePin(MOTOR4A_GPIO_Port,MOTOR4A_Pin,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(MOTOR4B_GPIO_Port,MOTOR4B_Pin,GPIO_PIN_SET);
}

void BRAKE(void){
	HAL_GPIO_WritePin(MOTOR1A_GPIO_Port,MOTOR1A_Pin,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(MOTOR1B_GPIO_Port,MOTOR1B_Pin,GPIO_PIN_RESET);
	
	HAL_GPIO_WritePin(MOTOR2A_GPIO_Port,MOTOR2A_Pin,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(MOTOR2B_GPIO_Port,MOTOR2B_Pin,GPIO_PIN_RESET);
	
	HAL_GPIO_WritePin(MOTOR3A_GPIO_Port,MOTOR3A_Pin,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(MOTOR3B_GPIO_Port,MOTOR3B_Pin,GPIO_PIN_RESET);
	
	HAL_GPIO_WritePin(MOTOR4A_GPIO_Port,MOTOR4A_Pin,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(MOTOR4B_GPIO_Port,MOTOR4B_Pin,GPIO_PIN_RESET);
}
